apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pal-tracker
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pal-tracker
  targetCPUUtilizationPercentage: 80
