apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: mbergquist/pal-tracker:build-12
          envFrom:
            - secretRef:
                name: db-credentials
          resources:
            limits:
              cpu: "100m"
          readinessProbe:
            httpGet:
               path: /
               port: 8080
          lifecycle:
            preStop:
              exec:
               command: [ "/bin/sleep", "10" ]
          env:
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: pal-tracker
                key: welcome.message
          - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
            valueFrom:
              configMapKeyRef:
                name: pal-tracker
                key: spring.datasource.hikari.maximumpoolsize
