name: Pal Tracker Pipeline

on:
  push:
    branches: [master]

env:
  DOCKER_HUB_USERNAME: mbergquist
  GCP_PROJECT_NAME: k8s-349803653-mbergquist-vmwar
  K8S_CLUSTER_NAME: pal-for-devs-k8s

jobs:
  build-pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'
      - run: sudo apt update
      - run: sudo apt-get install postgresql-11
      - run: sudo -u postgres psql -f databases/tracker/create_databases.sql -U postgres
      - run: curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.3.1/flyway-commandline-6.3.1-linux-x64.tar.gz | tar xvz
      - run: ./flyway-6.3.1/flyway -url="jdbc:postgresql://localhost:5432/tracker_test" -locations=filesystem:databases/tracker clean migrate -user=tracker -password='password'
      - name: Build with Gradle
        run: ./gradlew build
      - run: sudo apt-get install docker
      - run: docker login -u "${{env.DOCKER_HUB_USERNAME}}" -p "${{secrets.DOCKER_HUB_PASSWORD}}"
      - run: wget https://github.com/buildpacks/pack/releases/download/v0.9.0/pack-v0.9.0-linux.tgz
      - run: tar xvf pack-v0.9.0-linux.tgz
      - run: rm pack-v0.9.0-linux.tgz
      - run: rm -rf flyway-6.3.1
      - run: ./pack build ${{env.DOCKER_HUB_USERNAME}}/pal-tracker:build-${{github.run_number}} --builder cloudfoundry/cnb:bionic --publish
  deploy:
    needs: build-pack-and-publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      - run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      - run: sudo apt-get update && sudo apt-get install google-cloud-sdk
      - run: echo '${{secrets.GCP_SERVICE_KEY}}' > google-key.json
      - run: gcloud auth activate-service-account --key-file="google-key.json"
      - run: gcloud container clusters get-credentials ${{env.K8S_CLUSTER_NAME}} --project ${{env.GCP_PROJECT_NAME}} --zone us-central1-c
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.10/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - uses: actions/checkout@v1
      - run: grep "github.run_number" k8s/environments/review/deployment.yaml
      - run: sed -i 's/github.run_number/${{github.run_number}}/g' k8s/environments/review/deployment.yaml
      - run: kubectl apply -k k8s/environments/review
      - run: curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.3.1/flyway-commandline-6.3.1-linux-x64.tar.gz | tar xvz
      - run: ./flyway-6.3.1/flyway -url="jdbc:postgresql://${{secrets.ELEPHANT_SQL_SERVER}}:5432/${{secrets.ELEPHANT_SQL_DATABASE}}" -locations=filesystem:databases/tracker migrate -user=${{secrets.ELEPHANT_SQL_USER}} -password=${{secrets.ELEPHANT_SQL_PASSWORD}}

